import type { UserListItem } from '@/src/types/user-management'

/** Placeholder data until user APIs are wired. */
export const MOCK_USERS: UserListItem[] = [
  {
    id: '0',
    name: 'Avery Chen',
    email: 'avery@acme.test',
    roles: ['Tenant Admin'],
    groups: ['Operations', 'Security'],
    department: 'Operations',
    country: 'United States',
    status: 'active',
    lastLogin: '2024-05-15',
    jobTitle: 'Director',
    phone: '+1 415 555 0101',
    territory: 'North America',
    region: 'US-West',
    businessUnit: 'Operations',
  },
  {
    id: '1',
    name: 'Alex Morgan',
    email: 'alex.morgan@example.com',
    roles: ['Tenant Admin'],
    groups: ['Operations'],
    department: 'Operations',
    country: 'United States',
    status: 'active',
    lastLogin: '2026-05-18',
    jobTitle: 'Director of Operations',
    phone: '+1 555 0100',
  },
  {
    id: '2',
    name: 'Priya Shah',
    email: 'priya.shah@example.com',
    roles: ['Operations Manager'],
    groups: ['Operations', 'Security'],
    department: 'Operations',
    country: 'United Kingdom',
    status: 'active',
    lastLogin: '2026-05-17',
    jobTitle: 'Operations Manager',
  },
  {
    id: '3',
    name: 'Jordan Lee',
    email: 'jordan.lee@example.com',
    roles: ['Viewer'],
    groups: [],
    department: 'Finance',
    country: 'Singapore',
    status: 'pending',
    lastLogin: null,
    jobTitle: 'Financial Analyst',
  },
  {
    id: '4',
    name: 'Sam Rivera',
    email: 'sam.rivera@example.com',
    roles: ['Viewer'],
    groups: ['Security'],
    department: 'Customer Support',
    country: 'United States',
    status: 'active',
    lastLogin: '2026-05-10',
  },
  {
    id: '5',
    name: 'Taylor Brooks',
    email: 'taylor.brooks@example.com',
    roles: ['Operations Manager', 'Viewer'],
    groups: ['Operations'],
    department: 'Operations',
    country: 'Canada',
    status: 'pending',
    lastLogin: null,
  },
]
