import type { UserListItem } from '@/src/types/user-management'

/** Placeholder data until user APIs are wired. */
export const MOCK_USERS: UserListItem[] = [
  {
    id: '0',
    name: 'Avery Chen',
    email: 'avery@acme.test',
    roles: ['Tenant Admin'],
    groups: ['Operations', 'Security'],
    department: 'Administration',
    office: 'Kadel Labs, Singhvi Square, IT Park, Madri, Udaipur, Rajasthan 313001, India',
    status: 'active',
    lastLogin: '2024-05-15',
    jobTitle: 'Director',
    phone: '+1 415 555 0101',
    territory: 'America',
    region: 'US-West',
    businessUnit: 'Operations',
  },
  {
    id: '1',
    name: 'Alex Morgan',
    email: 'alex.morgan@example.com',
    roles: ['Tenant Admin'],
    groups: ['Operations'],
    department: 'Sales',
    office: 'Kadel Labs, Singhvi Square, IT Park, Madri, Udaipur, Rajasthan 313001, India',
    status: 'active',
    lastLogin: '2026-05-18',
    jobTitle: 'Director of Operations',
    territory: 'America',
    phone: '+1 555 0100',
  },
  {
    id: '2',
    name: 'Priya Shah',
    email: 'priya.shah@example.com',
    roles: ['Operations Manager'],
    groups: ['Operations', 'Security'],
    department: 'IT',
    office: 'Kadel Labs Corporate Office, Corporate Office, Jaipur, Rajasthan 302001, India',
    status: 'active',
    lastLogin: '2026-05-17',
    jobTitle: 'Operations Manager',
    territory: 'Europe',
  },
  {
    id: '3',
    name: 'Jordan Lee',
    email: 'jordan.lee@example.com',
    roles: ['Viewer'],
    groups: [],
    department: 'Finance',
    office: 'Kadel Labs Technology Center, Technology Center, Ahmedabad, Gujarat 380001, India',
    status: 'pending',
    lastLogin: null,
    jobTitle: 'Financial Analyst',
    territory: 'Asia',
  },
  {
    id: '4',
    name: 'Sam Rivera',
    email: 'sam.rivera@example.com',
    roles: ['Viewer'],
    groups: ['Security'],
    department: 'Marketing',
    office: 'Kadel Labs, Singhvi Square, IT Park, Madri, Udaipur, Rajasthan 313001, India',
    status: 'active',
    lastLogin: '2026-05-10',
    territory: 'America',
  },
  {
    id: '5',
    name: 'Taylor Brooks',
    email: 'taylor.brooks@example.com',
    roles: ['Operations Manager', 'Viewer'],
    groups: ['Operations'],
    department: 'HR',
    office: 'Kadel Labs Corporate Office, Corporate Office, Jaipur, Rajasthan 302001, India',
    status: 'pending',
    lastLogin: null,
    territory: 'America',
  },
]
