import type { UserRow } from '@/src/types/user-management'

export const MOCK_USERS: UserRow[] = [
  {
    id: 'u1',
    userName: 'Aisha Kapoor',
    email: 'aisha.kapoor@oomnieye.io',
    age: 34,
    mobileNumber: '+91 98200 11223',
    role: 'Security Admin',
    group: 'Command North',
    location: 'Mumbai, India',
    status: 'Active',
  },
  {
    id: 'u2',
    userName: 'Marcus Chen',
    email: 'marcus.chen@oomnieye.io',
    age: 41,
    mobileNumber: '+1 415 555 0198',
    role: 'Operator',
    group: 'Patrol West',
    location: 'San Francisco, USA',
    status: 'Active',
  },
  {
    id: 'u3',
    userName: 'Elena Rossi',
    email: 'elena.rossi@oomnieye.io',
    age: 29,
    mobileNumber: '+39 06 5555 4411',
    role: 'Auditor',
    group: 'Compliance',
    location: 'Rome, Italy',
    status: 'Pending',
  },
  {
    id: 'u4',
    userName: 'James Okafor',
    email: 'j.okafor@oomnieye.io',
    age: 37,
    mobileNumber: '+234 803 555 2211',
    role: 'Site Supervisor',
    group: 'Field Ops',
    location: 'Lagos, Nigeria',
    status: 'Inactive',
  },
  {
    id: 'u5',
    userName: 'Priya Desai',
    email: 'priya.desai@oomnieye.io',
    age: 33,
    mobileNumber: '+91 99876 55443',
    role: 'Security Admin',
    group: 'Command North',
    location: 'Jaipur, India',
    status: 'Active',
  },
  {
    id: 'u6',
    userName: 'Noah Williams',
    email: 'noah.williams@oomnieye.io',
    age: 45,
    mobileNumber: '+44 20 7946 0958',
    role: 'Operator',
    group: 'Patrol West',
    location: 'London, UK',
    status: 'Active',
  },
  {
    id: 'u7',
    userName: 'Sofia Martinez',
    email: 'sofia.martinez@oomnieye.io',
    age: 31,
    mobileNumber: '+34 91 555 7788',
    role: 'IoT Engineer',
    group: 'IoT Lab',
    location: 'Madrid, Spain',
    status: 'Active',
  },
  {
    id: 'u8',
    userName: 'Daniel Kim',
    email: 'daniel.kim@oomnieye.io',
    age: 27,
    mobileNumber: '+82 10 5555 6622',
    role: 'Operator',
    group: 'Command North',
    location: 'Seoul, South Korea',
    status: 'Pending',
  },
]

export const MOCK_ROLE_OPTIONS = [
  'Super Admin',
  'Security Admin',
  'Operator',
  'Auditor',
  'Site Supervisor',
  'IoT Engineer',
  'Read Only',
]

export const MOCK_GROUP_OPTIONS = [
  'Command North',
  'Patrol West',
  'Compliance',
  'Field Ops',
  'IoT Lab',
  'Executive',
]
