import type { ReportGroup, ReportPinType, ReportPlacemark } from '@/types/report-placemark'

const now = () => new Date()

function pm(
  partial: Omit<
    ReportPlacemark,
    'id' | 'createdAt' | 'updatedAt' | 'groupIds' | 'pinType'
  > & { pinType: ReportPinType; id: string; groupIds?: string[] },
): ReportPlacemark {
  const t = now()
  return {
    groupIds: partial.groupIds ?? [],
    createdAt: t,
    updatedAt: t,
    ...partial,
  }
}

function grp(
  id: string,
  pinType: ReportPinType,
  name: string,
  parentGroupIds: string[] = [],
): ReportGroup {
  const t = now()
  return { id, pinType, name, parentGroupIds, createdAt: t, updatedAt: t }
}

/** Mock groups (scoped by pinType). IDs stable for mock placemark groupIds. */
export const mockReportGroups: ReportGroup[] = [
  grp('rg-places-north', 'places', 'North campus', []),
  grp('rg-places-north-a', 'places', 'Building A', ['rg-places-north']),
  grp('rg-camera-main', 'camera', 'Main feeds', []),
  grp('rg-patrol-weekly', 'site_patrol', 'Weekly routes', []),
  grp('rg-assets-veh', 'assets', 'Fleet', []),
  grp('rg-iots-sensors', 'iots', 'Floor sensors', []),
]

export const mockReportPlacemarks: ReportPlacemark[] = [
  pm({
    id: 'rpm-pl-1',
    pinType: 'places',
    placemarkName: 'Main entrance',
    pinIcon: 'places',
    iconColor: '#3b82f6',
    category: 'Access',
    tags: ['public', 'gate'],
    city: 'Austin',
    country: 'USA',
    region: 'Texas',
    latitude: 30.2672,
    longitude: -97.7431,
    altitude: 12,
    grounding: 'clampToGround',
    description: 'Primary visitor entrance with badge readers.',
    groupIds: ['rg-places-north'],
  }),
  pm({
    id: 'rpm-pl-2',
    pinType: 'places',
    placemarkName: 'Loading dock B',
    pinIcon: 'places',
    iconColor: '#22c55e',
    category: 'Logistics',
    tags: ['dock', 'hvac'],
    city: 'Austin',
    country: 'USA',
    region: 'Texas',
    latitude: 30.2681,
    longitude: -97.7418,
    altitude: 8,
    grounding: 'relative',
    description: 'Bay doors 4–6; truck queue zone.',
    groupIds: ['rg-places-north-a'],
  }),
  pm({
    id: 'rpm-pl-3',
    pinType: 'places',
    placemarkName: 'Roof helipad',
    pinIcon: 'map_pin',
    iconColor: '#eab308',
    category: 'Emergency',
    tags: ['roof', 'evac'],
    city: 'Austin',
    country: 'USA',
    region: 'Texas',
    latitude: 30.2675,
    longitude: -97.7425,
    altitude: 85,
    grounding: 'absolute',
    description: 'Marked H1; night lighting on circuit L7.',
    groupIds: [],
  }),
  pm({
    id: 'rpm-cam-1',
    pinType: 'camera',
    placemarkName: 'Lobby PTZ',
    pinIcon: 'camera',
    iconColor: '#ef4444',
    category: 'Interior',
    tags: ['ptz', 'lobby'],
    city: 'Denver',
    country: 'USA',
    region: 'Colorado',
    latitude: 39.7392,
    longitude: -104.9903,
    altitude: 3,
    grounding: 'clampToGround',
    description: 'Wide-angle lobby coverage; shared with events.',
    groupIds: ['rg-camera-main'],
  }),
  pm({
    id: 'rpm-cam-2',
    pinType: 'camera',
    placemarkName: 'Parking L2 east',
    pinIcon: 'camera',
    iconColor: '#a855f7',
    category: 'Parking',
    tags: ['lpr', 'night'],
    city: 'Denver',
    country: 'USA',
    region: 'Colorado',
    latitude: 39.739,
    longitude: -104.9895,
    altitude: -4,
    grounding: 'relative',
    description: 'Fixed dome; IR enabled.',
    groupIds: [],
  }),
  pm({
    id: 'rpm-sp-1',
    pinType: 'site_patrol',
    placemarkName: 'Perimeter check A',
    pinIcon: 'site_patrol',
    iconColor: '#0ea5e9',
    category: 'Patrol',
    tags: ['fence', 'q1'],
    city: 'Phoenix',
    country: 'USA',
    region: 'Arizona',
    latitude: 33.4484,
    longitude: -112.074,
    altitude: 5,
    grounding: 'clampToGround',
    description: 'Nightly sweep checkpoint; NFC tap required.',
    groupIds: ['rg-patrol-weekly'],
  }),
  pm({
    id: 'rpm-sp-2',
    pinType: 'site_patrol',
    placemarkName: 'Warehouse sweep',
    pinIcon: 'patrol',
    iconColor: '#14b8a6',
    category: 'Patrol',
    tags: ['indoor'],
    city: 'Phoenix',
    country: 'USA',
    region: 'Arizona',
    latitude: 33.449,
    longitude: -112.0732,
    altitude: 2,
    grounding: 'relative',
    description: 'Aisles 12–18; pair with handheld scanner.',
    groupIds: [],
  }),
  pm({
    id: 'rpm-as-1',
    pinType: 'assets',
    placemarkName: 'Generator G3',
    pinIcon: 'assets',
    iconColor: '#f97316',
    category: 'Power',
    tags: ['backup', 'diesel'],
    city: 'Seattle',
    country: 'USA',
    region: 'Washington',
    latitude: 47.6062,
    longitude: -122.3321,
    altitude: 1,
    grounding: 'clampToGround',
    description: '200kW standby; vibration sensor paired.',
    groupIds: ['rg-assets-veh'],
  }),
  pm({
    id: 'rpm-as-2',
    pinType: 'assets',
    placemarkName: 'Cold storage unit',
    pinIcon: 'box',
    iconColor: '#64748b',
    category: 'Cold chain',
    tags: ['temp', 'sensor'],
    city: 'Seattle',
    country: 'USA',
    region: 'Washington',
    latitude: 47.6055,
    longitude: -122.3314,
    altitude: 0,
    grounding: 'relative',
    description: 'Target -18°C; alerts on door open > 60s.',
    groupIds: [],
  }),
  pm({
    id: 'rpm-iot-1',
    pinType: 'iots',
    placemarkName: 'Temp sensor T-104',
    pinIcon: 'iots',
    iconColor: '#ec4899',
    category: 'Climate',
    tags: ['ble', 'hvac'],
    city: 'Portland',
    country: 'USA',
    region: 'Oregon',
    latitude: 45.5152,
    longitude: -122.6784,
    altitude: 15,
    grounding: 'absolute',
    description: 'Ceiling mount; reports every 5 minutes.',
    groupIds: ['rg-iots-sensors'],
  }),
  pm({
    id: 'rpm-iot-2',
    pinType: 'iots',
    placemarkName: 'Air quality node Q7',
    pinIcon: 'iot',
    iconColor: '#8b5cf6',
    category: 'Air',
    tags: ['pm25', 'co2'],
    city: 'Portland',
    country: 'USA',
    region: 'Oregon',
    latitude: 45.5148,
    longitude: -122.679,
    altitude: 14,
    grounding: 'relative',
    description: 'Lobby mezzanine; calibrate quarterly.',
    groupIds: [],
  }),
]
